# Generated by Django 5.0.6 on 2024-07-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('job', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('age', models.PositiveBigIntegerField(null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('experience', models.PositiveIntegerField(null=True)),
                ('work_time', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('min_salary', models.PositiveIntegerField(null=True)),
                ('max_salary', models.PositiveIntegerField(null=True)),
                ('min_experience', models.PositiveIntegerField(null=True)),
                ('max_experience', models.PositiveIntegerField(null=True)),
                ('work_time', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
