# Generated by Django 3.2.12 on 2024-07-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeModel',
        ),
        migrations.RemoveField(
            model_name='vacationmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='vacationmodel',
            name='currency',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vacationmodel',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
