# Generated by Django 5.0.6 on 2024-07-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_alter_vacationmodel_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationmodel',
            name='job',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
