# Generated by Django 5.0.6 on 2024-07-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_alter_vacationmodel_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationmodel',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacationmodel',
            name='job',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vacationmodel',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacationmodel',
            name='work_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
